# Generated by Django 3.1.3 on 2020-11-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
