# Generated by Django 3.1.2 on 2020-11-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20201119_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default=models.CharField(max_length=150, verbose_name='Kategoria'), max_length=160, unique=True),
        ),
    ]
