# Generated by Django 3.1.2 on 2020-11-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
