# Generated by Django 3.1.2 on 2020-11-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=150, verbose_name='Kategoria'), max_length=40),
        ),
    ]
